# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra-dm}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["kematzy"]
  s.date = %q{2010-06-09}
  s.description = %q{Sinatra Extension for working with DataMapper (another Sinatra-Sequel Rip-off)}
  s.email = %q{kematzy@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/sinatra/dm.rb",
     "sinatra-dm.gemspec",
     "spec/dm_bootstrap.rb",
     "spec/fixtures/db/.gitignore",
     "spec/fixtures/db/custom/.gitignore",
     "spec/fixtures/log/.gitignore",
     "spec/sinatra/dm_mysql_spec.rb",
     "spec/sinatra/dm_sqlite3_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kematzy/sinatra-dm}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Sinatra Extension for working with DataMapper}
  s.test_files = [
    "spec/dm_bootstrap.rb",
     "spec/sinatra/dm_mysql_spec.rb",
     "spec/sinatra/dm_sqlite3_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<dm-core>, ["= 1.0.0"])
      s.add_runtime_dependency(%q<kematzy-tasks>, [">= 0"])
      s.add_development_dependency(%q<sinatra-tests>, ["= 0.1.6"])
      s.add_development_dependency(%q<dm-migrations>, ["= 1.0.0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<dm-core>, ["= 1.0.0"])
      s.add_dependency(%q<kematzy-tasks>, [">= 0"])
      s.add_dependency(%q<sinatra-tests>, ["= 0.1.6"])
      s.add_dependency(%q<dm-migrations>, ["= 1.0.0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<dm-core>, ["= 1.0.0"])
    s.add_dependency(%q<kematzy-tasks>, [">= 0"])
    s.add_dependency(%q<sinatra-tests>, ["= 0.1.6"])
    s.add_dependency(%q<dm-migrations>, ["= 1.0.0"])
  end
end

